### ISSUE TITLE
Remove सम्भाषणसन्देशः appearing in top left corner of every page

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#46]
From J. Hegde:

ಜಾಲಪುಟದ ಎಡಬದಿಯ ಮೇಲ್ಗಡೆ सम्भाषणसन्देशः ಎಂದು ತೋರುತ್ತಿರುವುದಕ್ಕೆ ಯಾವುದೇ ಪ್ರಯೋಜನವೂ ಇಲ್ಲ. ಅದನ್ನು ತೆಗೆದುಬಿಡುವುದು ಒಳಿತು.

**Comment by Shruthisdst** [comment]
Commit No. 72

**Comment by Shruthisdst** [comment]
The above closed issue retained by Commit No. 75
