### ISSUE TITLE
Needed separate entry for each Book Review. Now they are combined

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#49]
From J. Hegde:

ಗ್ರಂಥ ಪರಿಚಯ ವಿಭಾಗದಲ್ಲಿ ಒಂದೊಂದು ತಿಂಗಳಲ್ಲೂ ಎರಡು ಮೂರು ಗ್ರಂಥಗಳ ಪರಿಚಯವಿರುತ್ತದೆ. ಅವುಗಳ ಹೆಸರು ಅನುಕ್ರಮಣಿಕೆಯಲ್ಲಿ ಬಂದರೆ ಮಾತ್ರ ಅವನ್ನು ಹುಡುಕಬಹುದಾಗಿದೆ. ಈಗ ಹುಡುಕಲು ಆಗುತ್ತಿಲ್ಲ.

**Comment by arjunkashyap** [comment]
Assigned to Bhagyalakshmi.

**Comment by shivasdst** [comment]
Closed Issue.  Commit No. 88
