### ISSUE TITLE
Include the title appearing below Bhashapakaha. At present there is no title

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#50]
From J. Hegde:

ಭಾಷಾಪಾಕದ ಶಿರೋನಾಮೆ ಸೇರಿಸಬೇಕು. ಅದನ್ನು ಹುಡುಕುವುದಕ್ಕೆ ವ್ಯವಸ್ಥೆ ಆಗಬೇಕು. ಈಗ ೧,೨ ...ಎಂದು ಮಾತ್ರ ಇದೆ.

**Comment by arjunkashyap** [comment]
Assigned to Bhagyalakshmi.

**Comment by shivasdst** [comment]
Commit No. 87. Issue closed
