### ISSUE TITLE
Include feedback form in Contact page. 

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#52]
From J. Hegde:

ವಾಚಕರು Feed back (प्रतिपुष्टिः) ತಿಳಿಸಲು ಬಯಸಿದಲ್ಲಿ ಅದಕ್ಕೆ ಬೇಕಾದ ವ್ಯವಸ್ಥೆ ಆಗಿಲ್ಲ ತಾನೆ ?

**Comment by shivasdst** [comment]
Replace Contact by Feedback | प्रतिपुष्टिः and use sendmail library instead of mail.

**Comment by arjunkashyap** [comment]
recaptcha to be included. arjunkashyap/kscst-mvc repo could be used.
