### ISSUE TITLE
Google analytics to be included in the home page

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#54]
From J. Hegde:

ನಮ್ಮ ಜಾಲತಾಣಕ್ಕೆ ಭೇಟಿ ಕೊಟ್ಟವರ ವಿವರ ನಮಗೆ ಸಿಗುವಂತೆ ಮಾಡುವ ವ್ಯವಸ್ಥೆ ಏನಾಯಿತು ?

**Comment by arjunkashyap** [comment]
Analytics key has already been generated. To be included.

**Comment by arjunkashyap** [comment]
Implemented as Commit No. 88.
