### ISSUE TITLE
Special Issues?

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/Sambhashanasandesha#55]
From J. Hegde:

ವಿಶೇಷಾಂಕಗಳನ್ನು ಸೇರಿಸುವ ಕೆಲಸ ಯಾವಾಗ ಮುಗಿಯಬಹುದು ?

**Comment by arjunkashyap** [comment]
DjVu, PDF, JPG done and uploaded
XML with advt to be uploaded first and then advts could be included

**Comment by arjunkashyap** [comment]
Implemented in various commits. PDF yet to be uploaded.
